'''
run query and export data to gsheet
'''

from datetime import datetime
import csv
from google.cloud import bigquery
import logging

import gspread
from util.helper import get_logging_format
from oauth2client.service_account import ServiceAccountCredentials
from config.conf import key_path



logger: logging.Logger = get_logging_format()


def bq_query():
    """
    Extract Data from Bigquery table with prepared query
    """

    logger.info("creating csv file...")

    date_fmt = datetime.now().strftime("%Y%m%d") + ".csv"
    file_name = "mas_monthly_foreign_arr" + date_fmt

    bqclient = bigquery.Client.from_service_account_json(key_path)
    
    job_config = bigquery.QueryJobConfig(allow_large_results=True)

    query_loc = './sql/query.sql'
    sql_file = open(query_loc, 'r')
    query_string = sql_file.read()

    sql_file.close()

    # make api request to run query
    logger.info("running sql query script...")
    query_job = bqclient.query(query_string, job_config=job_config)

    # wait for job to complete
    query_job.result()

    dataframe = bqclient.query(query_string).to_dataframe(create_bqstorage_client=True)
    dataframe.set_index('date', inplace=True) # to remove the index number (generated by python when using pandas)
    # dataframe = dataframe.drop(dataframe.columns[0], axis=1)
    # dataframe = dataframe.reset_index(drop=True)
    print(dataframe.head())

    dataframe.to_csv(file_name) # output path and file_name

    logger.info("export to csv: %s", file_name)
    logger.info("Number of rows exported: %d", len(dataframe))
    logger.info(len(dataframe))

    # return file_name
    load_gsheet(file_name)


# SERVICE_ACCOUNT_FILE = 'key.json' # cred to allow that access

def load_gsheet(file_name):

    logger.info("uploading data to Google Sheet...")

    # Set up authentication for Google Sheets
    SCOPES = ['https://spreadsheets.google.com/feeds', 
            'https://www.googleapis.com/auth/drive'] # asking for access to the scope

    credentials = ServiceAccountCredentials.from_json_keyfile_name(key_path, scopes=SCOPES)
    client = gspread.authorize(credentials)

    # Load the CSV file
    # csv_file = 'path/to/your-file.csv'  # Replace with the path to your CSV file
    # with open(csv_file, 'r') as file:
    #     csv_data = file.read()

    with open(file_name, 'r') as file:
   #    csv_data = file.read()
        csv_reader = csv.reader(file, delimiter=',')
        csv_data = list(csv_reader)

    # Create a new Google Sheet
    sheet = client.open('mas_monthly_foreign_arr')

    # Write the CSV data to the sheet
    worksheet = sheet.get_worksheet(0)  # write to the first worksheet
    worksheet.update('A1', csv_data)

    logger.info("Data uploaded to Google Sheet successfully...")
